server:
  port: 8083
spring:
  application:
    name: message-test
  rabbitmq:
    host: xxxx
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual
        # 关闭失敗重新入队
        default-requeue-rejected: false
#  cloud:
#    stream:
#      default-binder: rabbit
#      binders:
#        rabbit:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: xxxx
#                port: 5672
##                virtual-host: /
#      bindings:
#        test-stream-in:
#          destination: test-stream
#          binder: rabbit
#          consumer:
#            durable-subscription: true
#            acknowledge-mode: manual
#            request-rejected: false
#            concurrency: 1
#        test-stream-out:
#          destination: test-stream
#          binder: rabbit
#        fail-test-stream-in:
#          destination: test-stream
#          binder: rabbit
#        fail-test-stream-out:
#          destination: fail-test-stream
#          binder: rabbit
