server:
  port: 8083
spring:
  application:
    name: message-test
  rabbitmq:
    host: xxx
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual
        # 关闭失敗重新入队
        default-requeue-rejected: false

